version: '3.1'

services:

  db:
    image: mariadb
    restart: "no"
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: passwd
      MARIADB_ROOT_PASSWORD: passwd
    ports:
      - "3306:3306"