# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: "no"
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: passwd
      MARIADB_ROOT_PASSWORD: passwd
    ports:
      - "3306:3306"

  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passwd
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/