version: '3.9'

services:

  postgres:
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: book_club
    volumes: 
      - ~/.SQLDBData/postgre/teste:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  
  mongo:
    image: mongo
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passwd

  mongo-express:
    image: mongo-express
    restart: no
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/